export const AUDIT_EVENTS = {
  USER_REGISTERED: 'USER_REGISTERED',
  EMAIL_VERIFICATION_SENT: 'EMAIL_VERIFICATION_SENT',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  NEW_DEVICE_LOGIN: 'NEW_DEVICE_LOGIN',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  LOGOUT: 'LOGOUT',
  LOGOUT_ALL: 'LOGOUT_ALL',
  SESSION_REVOKED: 'SESSION_REVOKED',
  ALL_SESSIONS_REVOKED: 'ALL_SESSIONS_REVOKED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  AVATAR_UPDATED: 'AVATAR_UPDATED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',

  // Module 2 Audit Events
  CLASSROOM_CREATED: 'CLASSROOM_CREATED',
  CLASSROOM_UPDATED: 'CLASSROOM_UPDATED',
  CLASSROOM_ARCHIVED: 'CLASSROOM_ARCHIVED',
  CLASSROOM_RESTORED: 'CLASSROOM_RESTORED',
  CLASSROOM_CODE_REGENERATED: 'CLASSROOM_CODE_REGENERATED',

  STUDENT_JOINED_CLASSROOM: 'STUDENT_JOINED_CLASSROOM',
  STUDENT_LEFT_CLASSROOM: 'STUDENT_LEFT_CLASSROOM',
  STUDENT_REMOVED: 'STUDENT_REMOVED',
  STUDENT_BLOCKED: 'STUDENT_BLOCKED',
  STUDENT_UNBLOCKED: 'STUDENT_UNBLOCKED',

  SCHEDULE_CREATED: 'SCHEDULE_CREATED',
  SCHEDULE_UPDATED: 'SCHEDULE_UPDATED',
  SCHEDULE_DELETED: 'SCHEDULE_DELETED',

  ANNOUNCEMENT_CREATED: 'ANNOUNCEMENT_CREATED',
  ANNOUNCEMENT_PUBLISHED: 'ANNOUNCEMENT_PUBLISHED',
  ANNOUNCEMENT_UPDATED: 'ANNOUNCEMENT_UPDATED',
  ANNOUNCEMENT_ARCHIVED: 'ANNOUNCEMENT_ARCHIVED',

  // Module 3 Attendance Audit Events
  ATTENDANCE_SESSION_CREATED: 'ATTENDANCE_SESSION_CREATED',
  ATTENDANCE_SESSION_STARTED: 'ATTENDANCE_SESSION_STARTED',
  ATTENDANCE_SESSION_EXTENDED: 'ATTENDANCE_SESSION_EXTENDED',
  ATTENDANCE_SESSION_ENDED: 'ATTENDANCE_SESSION_ENDED',
  ATTENDANCE_SESSION_CANCELLED: 'ATTENDANCE_SESSION_CANCELLED',
  ATTENDANCE_SESSION_EXPIRED: 'ATTENDANCE_SESSION_EXPIRED',

  ATTENDANCE_QR_ROTATED: 'ATTENDANCE_QR_ROTATED',
  ATTENDANCE_QR_REGENERATION_FAILED: 'ATTENDANCE_QR_REGENERATION_FAILED',

  ATTENDANCE_ATTEMPT_ACCEPTED: 'ATTENDANCE_ATTEMPT_ACCEPTED',
  ATTENDANCE_ATTEMPT_REJECTED: 'ATTENDANCE_ATTEMPT_REJECTED',
  ATTENDANCE_ATTEMPT_FLAGGED: 'ATTENDANCE_ATTEMPT_FLAGGED',
  ATTENDANCE_DUPLICATE_DETECTED: 'ATTENDANCE_DUPLICATE_DETECTED',

  ATTENDANCE_RECORD_CREATED: 'ATTENDANCE_RECORD_CREATED',
  ATTENDANCE_ABSENCE_MARKED: 'ATTENDANCE_ABSENCE_MARKED',
  ATTENDANCE_RECORD_CORRECTED: 'ATTENDANCE_RECORD_CORRECTED',
  ATTENDANCE_PENDING_APPROVED: 'ATTENDANCE_PENDING_APPROVED',
  ATTENDANCE_PENDING_REJECTED: 'ATTENDANCE_PENDING_REJECTED',

  ATTENDANCE_DEVICE_TRUSTED: 'ATTENDANCE_DEVICE_TRUSTED',
  ATTENDANCE_DEVICE_FLAGGED: 'ATTENDANCE_DEVICE_FLAGGED',
  ATTENDANCE_DEVICE_REVOKED: 'ATTENDANCE_DEVICE_REVOKED',

  ATTENDANCE_CHALLENGE_CREATED: 'ATTENDANCE_CHALLENGE_CREATED',
  ATTENDANCE_CHALLENGE_PASSED: 'ATTENDANCE_CHALLENGE_PASSED',
  ATTENDANCE_CHALLENGE_FAILED: 'ATTENDANCE_CHALLENGE_FAILED',
};
