import { ROLES } from './roles.js';

export const PERMISSIONS = {
  READ_PROFILE: [ROLES.STUDENT, ROLES.TEACHER, ROLES.ADMIN],
  UPDATE_PROFILE: [ROLES.STUDENT, ROLES.TEACHER],
  MANAGE_SESSIONS: [ROLES.STUDENT, ROLES.TEACHER, ROLES.ADMIN],
  ADMIN_ACCESS: [ROLES.ADMIN],
};
