import { env } from './env.js';

export const ATTENDANCE_CONFIG = {
  HMAC_SECRET: process.env.ATTENDANCE_HMAC_SECRET || env.ATTENDANCE_HMAC_SECRET || 'classiq_hmac_secret_key_2026_dev_mode_secret_key_min_32_bytes_long',
  QR_ROTATION_SECONDS: parseInt(process.env.ATTENDANCE_QR_ROTATION_SECONDS || '15', 10),
  DEFAULT_SESSION_MINUTES: parseInt(process.env.ATTENDANCE_DEFAULT_SESSION_MINUTES || '10', 10),
  MAX_SESSION_MINUTES: parseInt(process.env.ATTENDANCE_MAX_SESSION_MINUTES || '120', 10),
  DEFAULT_GEOFENCE_METERS: parseInt(process.env.ATTENDANCE_DEFAULT_GEOFENCE_METERS || '100', 10),
  MAX_GEOFENCE_METERS: parseInt(process.env.ATTENDANCE_MAX_GEOFENCE_METERS || '1000', 10),
  LATE_AFTER_MINUTES: parseInt(process.env.ATTENDANCE_LATE_AFTER_MINUTES || '5', 10),
  NONCE_BYTES: parseInt(process.env.ATTENDANCE_NONCE_BYTES || '16', 10),
  CLOCK_SKEW_TOLERANCE_SECONDS: parseInt(process.env.ATTENDANCE_MAX_TOKEN_CLOCK_SKEW_SECONDS || '10', 10),
  DEVICE_TRUST_DAYS: parseInt(process.env.ATTENDANCE_DEVICE_TRUST_DAYS || '30', 10),
  SUSPICION_REVIEW_THRESHOLD: parseInt(process.env.ATTENDANCE_SUSPICION_REVIEW_THRESHOLD || '40', 10),
  SUSPICION_REJECT_THRESHOLD: parseInt(process.env.ATTENDANCE_SUSPICION_REJECT_THRESHOLD || '70', 10),
  MAX_GPS_ACCURACY_METERS: parseInt(process.env.ATTENDANCE_MAX_GPS_ACCURACY_METERS || '150', 10),
};
