export class AICitationService {
  /**
   * Verifies that generated response citations accurately match retrieved context chunks.
   */
  static filterValidCitations(rawCitations = [], retrievedCitations = []) {
    if (!Array.isArray(retrievedCitations) || retrievedCitations.length === 0) {
      return [];
    }

    const retrievedMap = new Map();
    retrievedCitations.forEach((c) => {
      if (c.resourceId) {
        retrievedMap.set(c.resourceId.toString(), c);
      }
    });

    // If raw citations were generated by LLM, align them with retrieved metadata
    if (Array.isArray(rawCitations) && rawCitations.length > 0) {
      const valid = [];
      for (const raw of rawCitations) {
        const match = retrievedMap.get(raw.resourceId?.toString());
        if (match) {
          valid.push(match);
        }
      }
      if (valid.length > 0) return valid;
    }

    // Fallback: return unique retrieved citations
    const unique = [];
    const seen = new Set();
    for (const c of retrievedCitations) {
      const key = `${c.resourceId}_${c.pageNumber}`;
      if (!seen.has(key)) {
        seen.add(key);
        unique.push(c);
      }
    }
    return unique;
  }
}
