export const ATTENDANCE_ERROR_CODES = Object.freeze({
  ATTENDANCE_SESSION_NOT_FOUND: 'ATTENDANCE_SESSION_NOT_FOUND',
  ATTENDANCE_SESSION_ALREADY_ACTIVE: 'ATTENDANCE_SESSION_ALREADY_ACTIVE',
  ATTENDANCE_SESSION_INACTIVE: 'ATTENDANCE_SESSION_INACTIVE',
  ATTENDANCE_SESSION_ENDED: 'ATTENDANCE_SESSION_ENDED',
  ATTENDANCE_SESSION_EXPIRED: 'ATTENDANCE_SESSION_EXPIRED',

  ATTENDANCE_TOKEN_MALFORMED: 'ATTENDANCE_TOKEN_MALFORMED',
  ATTENDANCE_TOKEN_INVALID_SIGNATURE: 'ATTENDANCE_TOKEN_INVALID_SIGNATURE',
  ATTENDANCE_TOKEN_EXPIRED: 'ATTENDANCE_TOKEN_EXPIRED',
  ATTENDANCE_TOKEN_SESSION_MISMATCH: 'ATTENDANCE_TOKEN_SESSION_MISMATCH',
  ATTENDANCE_TOKEN_ROTATION_INVALID: 'ATTENDANCE_TOKEN_ROTATION_INVALID',

  ATTENDANCE_NOT_ENROLLED: 'ATTENDANCE_NOT_ENROLLED',
  ATTENDANCE_ALREADY_MARKED: 'ATTENDANCE_ALREADY_MARKED',
  ATTENDANCE_OUTSIDE_GEOFENCE: 'ATTENDANCE_OUTSIDE_GEOFENCE',
  ATTENDANCE_LOCATION_REQUIRED: 'ATTENDANCE_LOCATION_REQUIRED',
  ATTENDANCE_LOCATION_STALE: 'ATTENDANCE_LOCATION_STALE',
  ATTENDANCE_LOCATION_INVALID: 'ATTENDANCE_LOCATION_INVALID',

  ATTENDANCE_DEVICE_REVOKED: 'ATTENDANCE_DEVICE_REVOKED',
  ATTENDANCE_CHALLENGE_REQUIRED: 'ATTENDANCE_CHALLENGE_REQUIRED',
  ATTENDANCE_CHALLENGE_FAILED: 'ATTENDANCE_CHALLENGE_FAILED',

  ATTENDANCE_PENDING_REVIEW: 'ATTENDANCE_PENDING_REVIEW',
  ATTENDANCE_RATE_LIMITED: 'ATTENDANCE_RATE_LIMITED',
  ATTENDANCE_CORRECTION_FORBIDDEN: 'ATTENDANCE_CORRECTION_FORBIDDEN',
});
